/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        if (n <= 1) {
            return false;
        }

        for (long i = 2; i * i <= n; i++) {
            if (n % i == 0) {
                return false;
            }
        }
        //there is a syntax error error, the inital build should tell you that.
        return true
    }
    public long firstPrimeNumberIn(String n) {
        //Use Long.parseLong() vs Double.parseDouble to convert the 10 digit substring into a number.
        //more code goes here
    }
}
